# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa21465f4a238ffadc6480407709716fea0a6c9a49cc1f6eee7dc7342f063fc12519ee12f47e6a397f0de14b3cde46232019a574af9a82247314eed2ab1124c8

test:
  secret_key_base: 6a5746ce8b15c97623183f4e42b59598c14d5e404ed8b26fcb5264673d4d0d96c4203a0a3659835977bbdb196bd810527532f7f7d140d7665013500cdac7e5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
